import "@/node_modules/react-modal-video/css/modal-video.css";
import "swiper/css";
import "../public/assets/css/style.css";
// import "swiper/css/navigation"
import SessionProvider from "@/components/providers/SessionProvider";
import { dM_Sans } from "@/lib/font";
import "swiper/css/free-mode";
import "swiper/css/pagination";

export const metadata = {
  title: "Xafran Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${dM_Sans.variable}`}>
      <body>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
